[versions]
extra-java-module-info = "1.13"

jetbrains-annotations = "24.1.0"
jspecify = "1.0.0"
tiny-codecs = "5.1.0"

junit = "6.0.1"
vineflower = "1.11.2"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
tiny-codecs = { module = "fish.cichlidmc:tiny-codecs", version.ref = "tiny-codecs" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[bundles]
annotations = [ "jetbrains-annotations", "jspecify" ]
junit = [ "junit-jupiter", "junit-launcher" ]

[plugins]
java-library = { id = "java-library" }
maven-publish = { id = "maven-publish" }
extra-java-module-info = { id = "org.gradlex.extra-java-module-info", version.ref = "extra-java-module-info" }
